color0 #0e1214
color1 #e8b8a8
color2 #9dd2c0
color3 #c7e5db
color4 #a7cce1
color5 #b4e1e4
color6 #faddd2
color7 #abbcc4
color8 #151c1e
color9 #e8b8a8
color10 #9dd2c0
color11 #c7e5db
color12 #a7cce1
color13 #b4e1e4
color14 #faddd2
color15 #dbe2e6
background #0e1214
selection_foreground #abbcc4
cursor #abbcc4
cursor_text_color #0e1214
foreground #abbcc4
selection_background #212b30
active_border_color #9dd2c0
inactive_border_color #faddd2

active_tab_foreground   #0e1214
active_tab_background   #9dd2c0
inactive_tab_foreground #dbe2e6
inactive_tab_background #192024
cursor_trail_color      #dbe2e6
